categories = [
    "Best supporting actress",
    "Best makeup and hairstyling",
    "Best original score",
    "Best live action short film",
    "Best adapted screenplay",
    "Best original screenplay",
    "Best supporting actor",
    "Best animated short film",
    "Best casting",
    "Best original song",
    "Best documentary feature film",
    "Best documentary short film",
    "Best international feature film",
    "Best animated feature film",
    "Best production design",
    "Best film editing",
    "Best sound",
    "Best visual effects",
    "Best cinematography",
    "Best actor",
    "Best actress",
    "Best director",
    "Best picture",
    "Best costume design",
]

films = {
    "Sentimental Value": {
        "category": [
            "Best supporting actress",
            "Best original screenplay",
            "Best supporting actor",
            "Best international feature film",
            "Best film editing",
            "Best actress",
            "Best director",
            "Best picture",
        ],
        "cast_and_crew": [
            "Joachim Trier",
            "Eskil Vogt",
            "Olivier Bugge Coutté",
            "Elle Fanning",
            "Renate Reinsve",
            "Stellan Skarsgård",
            "Inga Ibsdotter Lilleaas",
        ],
        "genre": ["drama", "international"],
    },
    "Weapons": {
        "category": [
            "Best supporting actress",
        ],
        "cast_and_crew": [
            "Zach Cregger",
            "Julia Garner",
            "Josh Brolin",
            "Alden Ehrenreich",
            "Amy Madigan",
        ],
        "genre": ["horror", "mystery"],
    },
    "Sinners": {
        "category": [
            "Best supporting actress",
            "Best original score",
            "Best original screenplay",
            "Best supporting actor",
            "Best casting",
            "Best original song",
            "Best production design",
            "Best film editing",
            "Best sound",
            "Best visual effects",
            "Best cinematography",
            "Best actor",
            "Best director",
            "Best picture",
            "Best costume design",
        ],
        "cast_and_crew": [
            "Ryan Coogler",
            "Michael P. Shawver",
            "Ruth E. Carter",
            "Ludwig Göransson",
            "Michael B. Jordan",
            "Jack O'Connell",
            "Hailee Steinfeld",
            "Wunmi Mosaku",
            "Delroy Lindo",
            "Francine Maisler",
        ],
        "genre": [
            "action",
            "drama",
            "horror",
            "music",
            "thriller",
        ],
    },
    "One Battle After Another": {
        "category": [
            "Best supporting actress",
            "Best original score",
            "Best adapted screenplay",
            "Best supporting actor",
            "Best casting",
            "Best production design",
            "Best film editing",
            "Best sound",
            "Best cinematography",
            "Best actor",
            "Best director",
            "Best picture",
        ],
        "cast_and_crew": [
            "Paul Thomas Anderson",
            "Cassandra Kulukundis",
            "Andy Jurgensen",
            "Jonny Greenwood",
            "Leonardo DiCaprio",
            "Benicio Del Toro",
            "Sean Penn",
            "Teyana Taylor",
        ],
        "genre": [
          "action",
          "drama",
          "thriller",
        ],
    },
    "Frankenstein": {
        "category": [
            "Best makeup and hairstyling",
            "Best original score",
            "Best adapted screenplay",
            "Best supporting actor",
            "Best production design",
            "Best sound",
            "Best cinematography",
            "Best picture",
            "Best costume design",
        ],
        "cast_and_crew": [
            "Guillermo Del Toro",
            "Alexandre Desplat",
            "Kate Hawley",
            "Oscar Isaac",
            "Jacob Elordi",
            "Christoph Waltz",
            "Mia Goth",
        ],
        "genre": [
            "drama",
            "fantasy",
            "horror",
            "sci-fi",
        ],
    },
    "Kokuho": {
        "category": ["Best makeup and hairstyling"],
        "cast_and_crew": [
            "Sang-il Lee",
            "Satoko Okudera",
            "Shûichi Yoshida",
            "Ryô Yoshizawa",
            "Ryûsei Yokohama",
            "Mitsuki Takahata",
        ],
        "genre": [
            "drama",
            "international",
        ],
    },
    "The Smashing Machine": {
        "category": ["Best makeup and hairstyling"],
        "cast_and_crew": [
            "Benny Safdie",
            "Dwayne Johnson",
            "Emily Blunt",
            "Ryan Bader",
        ],
        "genre": [
            "action",
            "biography",
            "drama",
            "sport",
        ],
    },
    "The Ugly Stepsister": {
        "category": ["Best makeup and hairstyling"],
        "cast_and_crew": [
            "Emilie Blichfeldt",
            "Lea Myren",
            "Ane Dahl Torp",
            "Thea Sofie Loch Næss",
        ],
        "genre": [
            "comedy",
            "drama",
            "horror",
            "international",
        ],
    },
    "Bugonia": {
        "category": [
            "Best original score",
            "Best adapted screenplay",
            "Best actress",
            "Best picture",
        ],
        "cast_and_crew": [
            "Yorgos Lanthimos",
            "Will Tracy",
            "Jang Joon-hwan",
            "Jerskin Fendrix",
            "Emma Stone",
            "Jesse Plemons",
            "Aidan Delbis",
        ],
        "genre": [
            "comedy",
            "sci-fi",
            "thriller",
        ],
    },
    "Hamnet": {
        "category": [
            "Best original score",
            "Best adapted screenplay",
            "Best casting",
            "Best production design",
            "Best actress",
            "Best director",
            "Best picture",
            "Best costume design",
        ],
        "cast_and_crew": [
            "Chloé Zhao",
            "Maggie O'Farrell",
            "Max Richter",
            "Nina Gold",
            "Malgosia Turzanska",
            "Jessie Buckley",
            "Paul Mescal",
            "Zac Wishart",
        ],
        "genre": [
            "drama",
            "period",
            "romance",
        ],
    },
    "Train Dreams": {
        "category": [
            "Best adapted screenplay",
            "Best original song",
            "Best cinematography",
            "Best picture",
        ],
        "cast_and_crew": [
            "Clint Bentley",
            "Greg Kwedar",
            "Denis Johnson",
            "Joel Edgerton",
            "Clifton Collins Jr.",
            "Felicity Jones",
        ],
        "genre": [
            "drama",
            "period",
        ],
    },
}

genres = [
    "action",
    "biography",
    "comedy",
    "drama",
    "fantasy",
    "horror",
    "international",
    "music",
    "mystery",
    "period",
    "romance",
    "sci-fi",
    "short film",
    "sport",
    "thriller",
]
